manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: piit79
      url-base: https://github.com/piit79
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 2adaa00d1092e41ce11dfae46ce7d2a5bad97ead
      import: app/west.yml
    - name: zmk
      remote: piit79
      revision: fb48311b60f3b3675e6b2bd82c2691a16bd71300
  self:
    path: config
