manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      # TODO: Use a specific tag or branch
      revision: main
      import: app/west.yml
  self:
    path: config
